### PR TITLE
shared: Add PedConfigFlag

### PR DESCRIPTION
**Pull request by mrgharabaghi**

### CODE REVIEW

**Comment by mrgharabaghi** [comment]
https://github.com/altmp/altv-docs-gta/pull/62
Take a look at this.

**Comment by mrgharabaghi** [comment]
@LeonMrBonnie

**Comment by C0kkie** [comment]
@mrgharabaghi  please fix the conflict

**Comment by mrgharabaghi** [comment]
@C0kkie
https://github.com/altmp/altv-types/actions/runs/4898195129/jobs/8747070435

**Comment by C0kkie** [comment]
Why you delete the Ped class?

**Pull request merged**
