### PR TITLE
Add spatialVolume & nonSpatialVolume

### PR DESCRIPTION
**Pull request by C0kkie**

### CODE REVIEW

**Comment by FabianTerhorst** [comment]
We might wait a moment before merging this, because right now it looks like the volume is global setted and not per player.

**Comment by LeonMrBonnie** [comment]
The TSDoc comments are missing the `.` at the end of each sentence, pls fix

**Comment by C0kkie** [comment]
@FabianTerhorst  What you mean Heron?

**Comment by C0kkie** [comment]
@LeonMrBonnie added, its everytime again :(

**Comment by FabianTerhorst** [comment]
> @FabianTerhorst What you mean Heron?

there needs to be another update because its not correctly working yet, but type is correct.

**Comment by C0kkie** [comment]
Alright

**Comment by FabianTerhorst** [comment]
Fixed in 2.14

**Pull request merged**
